### ISSUE TITLE
Integrate NO_VALIDATE and NO_PICKLE Features Back into Django Core?

### ISSUE THREAD

**Issue by grantjenks** [kogan/django-lrucache-backend#4]
I noticed your cache improves performance over Django locmem cache in two ways:

1. It does not validate cache keys.
2. It does not pickle cache values.

I think those features should remain the default in Django core but they may be nice options to add. Are you interested in integrating those as options into Django?

**Comment by jarshwah** [comment]
Yes, I think those options would make sense in core. If they were available, I'd probably deprecate this project for Django >= 2.1 (assuming that'd be the target of such options).

**Comment by grantjenks** [comment]
Also note that Django's locmem cache now uses an LRU eviction policy.

I also don't think you need the lru-dict dependence. The collections.OrderedDict can be used instead. There's a [move_to_end](https://docs.python.org/3.6/library/collections.html#collections.OrderedDict.move_to_end) API that's used for the ``lru_cache`` decorator.

**Comment by jarshwah** [comment]
I'm aware of the LRU changes made to the built in loc-mem - but it requires collections.OrderedDict which only appeared in python 3.3, making the dependency required until Django 1.8 support is dropped.

I should benchmark against django 2.1 and do another one just using OrderedDict to see where they all lay. In the meantime, this package is still very useful for django 1.11 and 2.0.

**Comment by jarshwah** [comment]
Closing, as I think the latest 4.0.0 changes from #11 go far enough. It's unlikely Django would integrate the differences, even as an option, as it would depart from the interface too much. Especially since the replacement is relatively easy to vendor or add as a pip dependency.
