### ISSUE TITLE
RWLock is being deprecated and isn't the correct lock to use either

### ISSUE THREAD

**Issue by jarshwah** [kogan/django-lrucache-backend#5]
Since every read is actually a write (a read shifts the element to the back of the queue), then a read write lock is not sufficient. Further, RWLock is being deprecated from django core.

Remove reliance on RWLock and switch to threading.RLock.

See also #3 which will require a new set of benchmarks doing threaded benchmarking so that locks are engaged during testing.

**Comment by harrybiddle** [comment]
It looks like `RWLock` is now deleted as of version 2.1. I'll put in a PR to the README to indicate that this library is not yet compatible with 2.1+.

Any timeframe on this or suggestions of how I could contribute?

**Comment by jarshwah** [comment]
Since Django 2.1 switched to an LRU implementation (and hence removed the RWLock) there's no longer a big need for this package post 2.1. We have two options.

1. Mark this package as only working for < 2.1 and suggest users switch to the default LocMemCache for 2.1+

2. Update this package as discussed in the issue above (using RLock for reads and writes - can use the 2.1 Django LocMemCache for inspiration) as there might be **slightly** better performance/throughput with this package.

If we decide to go with 2, then we should run some new benchmarks. If you'd like to contribute by implementing 2 above I'd be happy to review/benchmark/release an update.

**Comment by jarshwah** [comment]
@harrybiddle I had some motivation and decided to try to fix the implementation so it would work for django 2.1+. Feel free to take a look at the linked PR. I'll try to release tomorrow.
