### ISSUE TITLE
When installing via poetry, can't use with Django 2.x

### ISSUE THREAD

**Issue by joshorr** [kogan/django-lrucache-backend#8]
It looks like the `pyproject.toml` lists the Django dependency as `Django = "^1.11"`, which means I can't use poetry to add `django-lrucache-backend` to a Django 2.x project.

The project read-me seems to indicate that Django 2.2 would be fine, but the pyproject.toml needs to be updated.

Here is my output when I try to add it to a Django 2.2 project:

```
[SolverProblemError]
Because django-lrucache-backend (2.0.0) depends on Django (>=1.11,<2.0)
 and no versions of django-lrucache-backend match >2.0.0,<3.0.0, django-lrucache-backend (>=2.0.0,<3.0.0) requires Django (>=1.11,<2.0).
So, because my_project depends on both django (^2.2.7) and django-lrucache-backend (^2.0.0), version solving failed.
```

**Comment by jarshwah** [comment]
https://docs.djangoproject.com/en/2.2/topics/cache/#local-memory-caching added the LRU eviction strategy in 2.1 which was the main feature of this library.

The other benefits of this library are around performance:

1. No serialization
2. No key character checks

I'm happy to accept a PR changing the dependencies to support Django > 1.11. One of our other projects has a similar dependency requirement you could base it off: https://github.com/kogan/django-subscriptions/blob/master/pyproject.toml

I'll likely make this change within the next couple of months anyway (as we move our main project away from 1.11), but I don't have the time for this right now. I'll merge and deploy any changes made sooner however.

**Comment by joshorr** [comment]
Sounds good.  It's the  no sterilization aspect I like about it.  I am using this to cache objects that are not pickable. I'll see if I can put something together, or I may just wait it out.

**Comment by valentijnscholten** [comment]
Just FYI, I am seeing same/similar with pip:

````
ERROR: django-lrucache-backend 2.0.0 has requirement Django<2.0,>=1.11, but you'll have django 2.2.4 which is incompatible.
````

**Comment by jarshwah** [comment]
Yup @valentijnscholten I haven't gotten around to this yet - but happy to accept/merge a PR to fix. Links above have examples that can be copied.
